#!/usr/bin/env bash
# TrailCam Alert installer.
#
#   curl -fsSL https://raw.githubusercontent.com/Riaan007/trailcam-install/main/install.sh | sudo bash
#
# Installs to /opt/trailcam with photos under /srv/trailcam, then prints a URL
# and a setup code. Everything else is done in the browser.
#
# Re-running is safe: an existing .env is reused, so secrets never change
# underneath a working install.
set -euo pipefail

REPO_RAW="${TRAILCAM_REPO_RAW:-https://raw.githubusercontent.com/Riaan007/trailcam-install/main}"
INSTALL_DIR="${TRAILCAM_DIR:-/opt/trailcam}"
DATA_DIR="${TRAILCAM_DATA:-/srv/trailcam}"
CONFIG_DIR="/etc/trailcam"
LOG_DIR="/var/log/trailcam"
REGISTRY="ghcr.io"
IMAGE_PREFIX="${TRAILCAM_IMAGE_PREFIX:-ghcr.io/riaan007}"
TAG="${TRAILCAM_TAG:-latest}"

RED=$'\033[31m'; GREEN=$'\033[32m'; YELLOW=$'\033[33m'; DIM=$'\033[2m'; OFF=$'\033[0m'
say()  { printf '%s\n' "$*"; }
ok()   { printf '  %s✓%s %s\n' "$GREEN" "$OFF" "$*"; }
warn() { printf '  %s!%s %s\n' "$YELLOW" "$OFF" "$*"; }
die()  { printf '  %s✗%s %s\n' "$RED" "$OFF" "$*" >&2; exit 1; }

# A tty is detected by OPENING /dev/tty, not by testing -t: this script is
# normally read from a pipe, and ssh without a pty is a real case.
HAS_TTY=0
if exec 3<>/dev/tty 2>/dev/null; then HAS_TTY=1; fi
ask() {  # ask <prompt> <default>
    local prompt="$1" default="${2:-}" reply=""
    if [ "$HAS_TTY" -eq 1 ]; then
        printf '%s%s' "$prompt" "${default:+ [$default]}" >&3
        printf ': ' >&3
        IFS= read -r reply <&3 || reply=""
    fi
    printf '%s' "${reply:-$default}"
}

[ "$(id -u)" -eq 0 ] || die "Run with sudo."

say ""
say "TrailCam Alert"
say "${DIM}Photos in by FTP, one alert per event, a web interface to review them.${OFF}"
say ""

# ---------------------------------------------------------------------------
# Preflight
# ---------------------------------------------------------------------------
say "Checking this machine"

ARCH="$(uname -m)"
case "$ARCH" in
    aarch64|arm64|x86_64|amd64) ok "Architecture $ARCH" ;;
    *) die "$ARCH is not supported. Images are built for arm64 and amd64." ;;
esac

if ! command -v docker >/dev/null 2>&1; then
    warn "Docker is not installed — installing it now"
    curl -fsSL https://get.docker.com | sh || die "Could not install Docker."
fi
docker compose version >/dev/null 2>&1 || die "This needs Docker Compose v2 (docker compose)."
ok "Docker $(docker --version | awk '{print $3}' | tr -d ,)"

# A TCP check is not enough: what fails on a farm link is the TLS handshake,
# and that is what took a whole site install down once already.
if ! curl -fsS --max-time 20 "https://$REGISTRY/v2/" >/dev/null 2>&1; then
    warn "Cannot complete a TLS handshake with $REGISTRY — the image pull may fail"
else
    ok "Registry reachable"
fi

for port in "${WEB_PORT:-8098}" 21; do
    if ss -tlnH "sport = :$port" 2>/dev/null | grep -q .; then
        die "Port $port is already in use. Free it, or set WEB_PORT before running this."
    fi
done
ok "Ports free"

mkdir -p "$DATA_DIR"/{incoming,archive,thumbs} "$CONFIG_DIR" "$LOG_DIR" "$INSTALL_DIR"

FREE_GB="$(df -BG --output=avail "$DATA_DIR" | tail -1 | tr -dc '0-9')"
[ "${FREE_GB:-0}" -ge 5 ] || die "Only ${FREE_GB}GB free on $DATA_DIR. Photos need room."
ok "${FREE_GB}GB free on $DATA_DIR"

# Trail cameras write constantly. An SD card will not survive it for long, and
# the failure mode is a corrupt filesystem rather than a warning.
SOURCE_DEV="$(df --output=source "$DATA_DIR" | tail -1)"
case "$SOURCE_DEV" in
    /dev/mmcblk*)
        warn "$DATA_DIR is on an SD card ($SOURCE_DEV)."
        warn "SD cards do not survive this write pattern. Point TRAILCAM_DATA at"
        warn "a USB SSD or an NVMe drive before you rely on this."
        ;;
    *) ok "Archive is on $SOURCE_DEV" ;;
esac

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------
say ""
say "Setting up $INSTALL_DIR"

cd "$INSTALL_DIR"
for file in docker-compose.yml selftest.sh trailcam; do
    if [ ! -f "$file" ] || [ "${TRAILCAM_FORCE:-0}" = "1" ]; then
        curl -fsSL "$REPO_RAW/$file" -o "$file" || die "Could not download $file"
    fi
done
chmod +x selftest.sh trailcam 2>/dev/null || true
ok "Downloaded the stack definition"

rand() { head -c 32 /dev/urandom | base64 | tr -dc 'A-Za-z0-9' | head -c "${1:-24}"; }

if [ -f .env ]; then
    # Re-runs must not roll the passwords of a working install.
    ok "Reusing the existing .env"
    SETUP_TOKEN="$(grep -E '^SETUP_TOKEN=' .env | cut -d= -f2- || true)"
else
    WEB_PORT="${WEB_PORT:-$(ask 'Port for the web interface' 8098)}"
    TZ_GUESS="$(cat /etc/timezone 2>/dev/null || echo UTC)"
    SETUP_TOKEN="$(rand 20)"
    cat > .env <<EOF
# Generated by install.sh on $(date -Is). Keep this file.
DB_ROOT_PASSWORD=$(rand 28)
DB_PASSWORD=$(rand 28)
DB_NAME=trailcam
DB_USER=trailcam
DB_PORT=3308

WEB_PORT=$WEB_PORT

FTP_PORT=21
PASV_MIN_PORT=40000
PASV_MAX_PORT=40100
# Set this to the address the CAMERA uses to reach this machine if it is
# behind NAT. On a LAN, leave it blank.
PASV_ADDRESS=

DATA_DIR=$DATA_DIR
CONFIG_FILE=$CONFIG_DIR/config.ini
LOG_DIR=$LOG_DIR
PUID=$(stat -c %u "$DATA_DIR")
PGID=$(stat -c %g "$DATA_DIR")

TZ=$TZ_GUESS

APP_IMAGE=$IMAGE_PREFIX/trailcam-app:$TAG
WEB_IMAGE=$IMAGE_PREFIX/trailcam-web:$TAG
FTP_IMAGE=$IMAGE_PREFIX/trailcam-ftp:$TAG

SETUP_TOKEN=$SETUP_TOKEN
EOF
    chmod 600 .env
    ok "Generated .env with fresh passwords"
fi

# shellcheck disable=SC1091
set -a; . ./.env; set +a

if [ ! -f "$CONFIG_DIR/config.ini" ]; then
    cat > "$CONFIG_DIR/config.ini" <<EOF
; TrailCam Alert — bootstrap only. Tuning lives on the System page, and every
; credential lives in the database, written by the setup wizard.
[paths]
incoming    = $DATA_DIR/incoming
archive     = $DATA_DIR/archive
thumbs      = $DATA_DIR/thumbs
log         = $LOG_DIR
min_free_gb = 2

[db]
host     = db
port     = 3306
user     = $DB_USER
password = $DB_PASSWORD
name     = $DB_NAME

; A feature is live only when its flag is on AND its credential is set, so
; everything ships on and stays silent until the wizard configures it.
[features]
yolo     = true
telegram = true
ntfy     = true
gemini   = true

[detect]
backend    = onnx
model      = /opt/trailcam/models/yolo11n.onnx
image_size = 640
max_frames_per_event = 6

[ingest]
settle_seconds   = 3
clock_skew_hours = 24
thumb_width      = 480

[web]
base_url = http://$(hostname -I 2>/dev/null | awk '{print $1}'):$WEB_PORT

[gemini]
model  = gemini-2.5-flash
prompt = Describe exactly what is visible in this trail camera photo in one or two plain sentences. Say how many people, vehicles or animals there are, what they are doing, and which way they are moving. Do not speculate about intent. If the frame is too dark or blurred to tell, say so plainly.
EOF
    chmod 600 "$CONFIG_DIR/config.ini"
    ok "Wrote $CONFIG_DIR/config.ini"
else
    ok "Keeping the existing $CONFIG_DIR/config.ini"
fi

chown -R "${PUID:-1000}:${PGID:-1000}" "$DATA_DIR" "$LOG_DIR"

# ---------------------------------------------------------------------------
# Images — pulled one at a time, because `docker compose pull` is
# all-or-nothing and one slow registry has taken a whole install down before.
# ---------------------------------------------------------------------------
say ""
say "Pulling images"

pull_one() {  # pull_one <service> <tries>
    local svc="$1" tries="${2:-3}" n=1 image
    image="$(docker compose config --images "$svc" 2>/dev/null | head -1)"

    while [ "$n" -le "$tries" ]; do
        if docker compose pull "$svc" >/dev/null 2>&1; then
            ok "$svc"
            return 0
        fi
        # Already on the machine is as good as pulled: covers a re-run, a site
        # with no working registry route, and an image loaded by hand from a
        # USB stick.
        if [ -n "$image" ] && docker image inspect "$image" >/dev/null 2>&1; then
            ok "$svc (already on this machine)"
            return 0
        fi
        warn "$svc pull failed (attempt $n of $tries)"
        sleep $((n * 10))
        n=$((n + 1))
    done
    return 1
}

pull_one db 3       || die "Could not pull MariaDB. Check the network and run this again."
pull_one watcher 4  || die "Could not pull the watcher image."
pull_one web 3      || die "Could not pull the web image."
pull_one ftp 3      || warn "Could not pull the FTP image — cameras cannot upload until it is there."

say ""
say "Starting"
docker compose up -d || die "The stack did not start. See: docker compose logs"

printf '  waiting for the database'
for _ in $(seq 1 60); do
    if docker compose exec -T db healthcheck.sh --connect >/dev/null 2>&1; then break; fi
    printf '.'
    sleep 2
done
printf '\n'

# The wizard is gated by this, so nobody on the LAN can claim a fresh install.
docker compose exec -T db mariadb -u"$DB_USER" -p"$DB_PASSWORD" "$DB_NAME" \
    -e "INSERT INTO secrets (name, value) VALUES ('setup_token', '$SETUP_TOKEN')
        ON DUPLICATE KEY UPDATE value = VALUES(value);" 2>/dev/null \
    || warn "Could not store the setup code — the wizard will accept a LAN connection instead"

IP="$(hostname -I 2>/dev/null | awk '{print $1}')"
say ""
say "${GREEN}Installed.${OFF}"
say ""
say "  Open        ${GREEN}http://${IP}:${WEB_PORT}${OFF}"
say "  Setup code  ${GREEN}${SETUP_TOKEN}${OFF}"
say ""
say "${DIM}The wizard makes your account, adds the first camera and prints the FTP"
say "details to type into it, then asks where alerts should go."
say ""
say "Afterwards:  cd $INSTALL_DIR && ./selftest.sh"
say "Update:      cd $INSTALL_DIR && docker compose pull && docker compose up -d${OFF}"
say ""
